# Generated by Django 3.1.1 on 2020-09-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['name'], 'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categorys'},
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
